---
services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - CLOUDSDK_CORE_PROJECT
      - CLOUDSDK_CONFIG=/gcp/config
      - GCLOUD_PROJECT=${CLOUDSDK_CORE_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/config/application_default_credentials.json
      - PORT=8080
      - TOPIC_NAME=api-events
    volumes:
      - ~/.config/gcloud:/gcp/config:ro
      - /gcp/config/logs
    ports:
      - 3001:8080

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - CLOUDSDK_CORE_PROJECT
      - CLOUDSDK_CONFIG=/gcp/config
      - GCLOUD_PROJECT=${CLOUDSDK_CORE_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/config/application_default_credentials.json
      - MONGO_HOST
      - MONGO_DATABASE
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - MONGO_REPLICA_SET
      - MONGO_TLS_CA_CRT=/etc/mongodb-tls/ca.crt
      - MONGO_TLS_KEY=/etc/mongodb-tls/tls.pem
      - MONGO_TLS_KEY_PASSWORD
      - SUBSCRIPTION
      - PULL=true
    volumes:
      - ~/.config/gcloud:/gcp/config:ro
      - /gcp/config/logs
      - ./certs:/etc/mongodb-tls
