---
version: '3'

networks:
  mongodb:
    driver: bridge

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - CLOUDSDK_CORE_PROJECT
      - CLOUDSDK_CONFIG=/gcp/config
      - GCLOUD_PROJECT=${CLOUDSDK_CORE_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/config/application_default_credentials.json
      - PORT=8080
      - TOPIC_NAME=api-events
    volumes:
      - ~/.config/gcloud:/gcp/config:ro
      - /gcp/config/logs
    ports:
      - 3001:8080
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - CLOUDSDK_CORE_PROJECT
      - CLOUDSDK_CONFIG=/gcp/config
      - GCLOUD_PROJECT=${CLOUDSDK_CORE_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/config/application_default_credentials.json
      - MONGO_HOST=mongo:27017
      - MONGO_DATABASE=otel_poc
      - MONGO_USERNAME=app
      - MONGO_PASSWORD
      - SUBSCRIPTION
      - PULL=true
    volumes:
      - ~/.config/gcloud:/gcp/config:ro
      - /gcp/config/logs
      - ./data:/data
    networks:
      - mongodb
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=app
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - mongodb
