#!/usr/bin/env bash

CLOUDSDK_CORE_PROJECT="${CLOUDSDK_CORE_PROJECT:-''}"
CLOUDSDK_COMPUTE_REGION="${CLOUDSDK_COMPUTE_REGION:-''}"
CONTAINER_REPO="${CONTAINER_REPO:-''}"
REGISTRY="${CLOUDSDK_COMPUTE_REGION}-docker.pkg.dev"

IMAGE_NAME="${1}"
IMAGE_VERSION="${2:-latest}"
IMAGE="${REGISTRY}/${CLOUDSDK_CORE_PROJECT}/${CONTAINER_REPO}/${IMAGE_NAME}:${IMAGE_VERSION}"

echo "${IMAGE}"
